PRAGMA journal_mode=WAL;
DROP TABLE IF EXISTS faqs;
CREATE TABLE faqs(id INTEGER PRIMARY KEY AUTOINCREMENT, question TEXT, answer TEXT);
DROP TABLE IF EXISTS leads;
CREATE TABLE leads(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, phone TEXT, email TEXT, message TEXT, raw_payload TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
